doctrine:
    dbal:
        url: '%env(resolve:DATABASE_URL)%'
        driver: pdo_pgsql
        # dbname: marketplace
        # user: marketplace
        # password: marketplace
        server_version: '%env(resolve:POSTGRES_VERSION)%'
    orm:
        auto_generate_proxy_classes: true
        naming_strategy: doctrine.orm.naming_strategy.underscore_number_aware
        auto_mapping: true
        mappings:
            Ajo\Tdd\Examples\Marketplace\Infrastructure\Entities:
                is_bundle: false
                dir: '%kernel.project_dir%/src/Infrastructure/Entities'
                prefix: 'Ajo\Tdd\Examples\Marketplace'
                alias: Marketplace\Entities

when@test:
    doctrine:
        dbal:
            # "TEST_TOKEN" is typically set by ParaTest
            #dbname_suffix: '_test%env(default::TEST_TOKEN)%'

when@prod:
    doctrine:
        orm:
            auto_generate_proxy_classes: false
            query_cache_driver:
                type: pool
                pool: doctrine.system_cache_pool
            result_cache_driver:
                type: pool
                pool: doctrine.result_cache_pool

    framework:
        cache:
            pools:
                doctrine.result_cache_pool:
                    adapter: cache.app
                doctrine.system_cache_pool:
                    adapter: cache.system
