services:
  marketplace:
    build:
      dockerfile: docker/Dockerfile.marketplace
      context: .
    ports:
        - "80:8080"
    mem_limit: 250m
    depends_on:
      - mariadb
    entrypoint: /usr/bin/startup.sh
    restart: on-failure
  mariadb:
    build:
      dockerfile: docker/Dockerfile.mariadb
      context: .
    mem_limit: 250m
    volumes:
      - ./var/database/:/var/projects/marketplace/database
    restart: on-failure